Blogs
uptech2021/Ourlime-Web pull request #19
Opened 2024-10-30 23:27 UTC by Quane-Dann-101

The completion of the blog page

2024-10-31 15:30 UTC, uptech2021 commented on app/blogs/page.tsx
>  type CategoriesProps = {
This hans't been used, if not needed. Please remove

2024-10-31 15:34 UTC, uptech2021 commented on app/blogs/page.tsx
>      const [categories, setCategories] = useState<Array<string>>([
You haven't used the setCategories function, if not needed you can change this to
```bash
let categories: Array<string> = [/* categories data */] 

The reason for this is, if you have unused variables in your project you are essentially creating a block in memory that is wasting memory. Hope that makes sense. It's like opening an app on your phone. You opened it and closed it, it's still running in the background wasting memory. So when you create a variable that hasn't been used, it's the same concept on wasting memory. It can also cause build issues.

2024-10-31 15:43 UTC, uptech2021 commented on components/blog/RecentArticles.tsx
> +                    {/* {filteredArticles.map((article, index) => (
You can remove lines 138-173 since you made the blogs into a card component

2024-10-31 15:47 UTC, uptech2021 commented on components/blog/RecentArticles.tsx
>  type Blog = {
Make this into a global type in the types folder because i noticed you also manually made another Blog type in the categories and recent articles components.

2024-10-31 15:55 UTC, uptech2021 requested changes
Well done, everything works fine. Note that i changed variables from ``Blogs``` to ```Articles```, it makes more sense seeing that the header is "Recent Articles", we can actually makes Blogs into a separate page.

When you make the changes i commented on you can push and I'll review again

2024-10-31 16:28 UTC, Quane-Dann-101 commented on app/blogs/page.tsx
>  type CategoriesProps = {
type CategoriesProps this is being used, Removing it would cause errors
<img width="539" alt="image" src="https://github.com/user-attachments/assets/3edce7b6-1879-414f-97e6-fb06bd9385c7">

2024-10-31 16:36 UTC, Quane-Dann-101 commented on app/blogs/page.tsx
>      const [categories, setCategories] = useState<Array<string>>([
I am not using setPost, so i changed const to let

2024-10-31 16:37 UTC, Quane-Dann-101 commented on components/blog/RecentArticles.tsx
>  import Image, { StaticImageData } from 'next/image';
understood, the change has been made

2024-10-31 16:41 UTC, Quane-Dann-101 commented on components/blog/RecentArticles.tsx
>  type Blog = {
not to sure what you mean

2024-11-01 00:29 UTC, uptech2021 requested changes
![image](https://github.com/user-attachments/assets/0433f84b-979d-4d53-9dcf-31f4c3c0bbe7)
You forgot to let the user know that there isn't items for what they filtered, same for searching, also search on type, rather than when they press enter. Non-technical persons might wonder why the form isn't searching:
![image](https://github.com/user-attachments/assets/1e82f540-08a1-46c6-8eb9-f4fc57afc79f)

2024-11-11 21:17 UTC, merged